<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2y8LVIX\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2y8LVIX/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2y8LVIX.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2y8LVIX\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \Container2y8LVIX\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => '2y8LVIX',
    'container.build_id' => 'b86de6ff',
    'container.build_time' => 1639865626,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2y8LVIX');
